version: '3.8'

services:
  jenkins_server:
    build:
      context: ./ci_cd       # 📍 Asegura que apunta a la carpeta con tu Dockerfile
      dockerfile: Dockerfile
    container_name: jenkins_server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_home:
