pipeline {
    agent any
    environment {
        AWS_REGION = "us-east-1"
        CHECKOV_REPORT = "checkov/results/scan_report.json"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'develop', url: 'https://github.com/DanielRumay/Lab_IF.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('terraform') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('terraform') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }

        stage('Run Checkov') {
            steps {
                sh 'mkdir -p checkov/results'
                sh 'checkov -d terraform -o json > ${CHECKOV_REPORT}'
                sh 'aws s3 cp ${CHECKOV_REPORT} s3://recetas-checkov/scan_report.json'
            }
        }
    }
}
