pipeline {
  agent any

  environment {
    TF_IN_AUTOMATION        = "true"
    AWS_REGION              = "us-east-1"
    AWS_ACCESS_KEY_ID       = credentials('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY   = credentials('AWS_SECRET_ACCESS_KEY')
  }

  options {
    skipStagesAfterUnstable()
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Terraform Init') {
      steps {
        dir('terraform') {
          sh 'terraform init'
        }
      }
    }

    stage('Terraform Plan') {
      steps {
        dir('terraform') {
          sh 'terraform plan -var-file=terraform.tfvars'
        }
      }
    }

    stage('Terraform Apply') {
      steps {
        input message: '¿Deseas aplicar los cambios con Terraform?'
        dir('terraform') {
          sh 'terraform apply -auto-approve -var-file=terraform.tfvars'
        }
      }
    }

    stage('Run Checkov') {
      steps {
        dir('ci_cd') {
          // Ejecutar Checkov y no detener el pipeline aunque falle
          sh 'bash checkov_scan.sh || true'
        }
      }
    }

  }

  post {
    failure {
      echo "❌ La ejecución del pipeline falló."
    }
    success {
      echo "✅ Pipeline ejecutado correctamente."
    }
  }
}


